services:

  app_name:
    container_name: app_name
    image: wallet-api-app
    ports:
      - "80:80"
    environment:
      - USER=<FILL_YOUR_USERNAME HERE>
      - AUTH_TOKEN=<FILL_YOUR_AUTH_TOKEN_HERE>
      - DB_HOST=<FILL_YOUR_DB_HOST_HERE>
      - DB_PORT=<FILL_YOUR_DB_PORT_HERE>
      - DB_NAME=<FILL_YOUR_DB_NAME_HERE>